#!/usr/bin/env node
// Generates hooks/pool.ts from registry.json (the name pool, carried over from the retired
// named-subagents Python package), so the mod needs no JSON import at runtime.
//   node scripts/gen_pool.mjs           write hooks/pool.ts
//   node scripts/gen_pool.mjs --check   exit 1 if hooks/pool.ts is stale
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const registryPath = join(here, '..', 'registry.json');
const outPath = join(here, '..', 'hooks', 'pool.ts');

const reg = JSON.parse(readFileSync(registryPath, 'utf8'));
const categories = Object.entries(reg.categories).map(([key, c]) => ({
  key, subagent_types: c.subagent_types ?? [], keywords: c.keywords ?? [], names: c.names,
}));
const out = `// GENERATED by scripts/gen_pool.mjs from registry.json. Do not edit.
import type { Pool } from './draw.ts';

export const POOL: Pool = ${JSON.stringify({ categories }, null, 2)};
`;

if (process.argv.includes('--check')) {
  let cur = '';
  try { cur = readFileSync(outPath, 'utf8'); } catch { cur = ''; }
  if (cur !== out) { console.error('hooks/pool.ts is stale: run node scripts/gen_pool.mjs'); process.exit(1); }
  console.log('hooks/pool.ts is current');
} else {
  writeFileSync(outPath, out);
  console.log(`wrote ${outPath}: ${categories.length} categories, ${categories.reduce((n, c) => n + c.names.length, 0)} names`);
}
